// Seed data for ACCA PM — used for quick practice widget & topic strength display

export const PRACTICE = [
  {
    id: 'pm-001', topic: 'Activity-Based Costing', topicNum: 4, paper: 'PM',
    session: 'Sep/Dec 2024', type: 'single', difficulty: 'Medium', marks: 2,
    prompt: "Beck Co manufactures three products. Total production overheads of $480,000 are currently absorbed on a labour-hour basis. Under ABC, the set-up cost pool is $120,000 driven by 200 production runs. Product Z requires 25 production runs. What is the set-up cost absorbed by Product Z under ABC?",
    options: { A: '$6,000', B: '$15,000', C: '$24,000', D: '$60,000' },
    correct: 'B',
    explanation: "Cost-driver rate = $120,000 ÷ 200 runs = $600 per run. Product Z absorbs 25 runs × $600 = $15,000.",
    calc: "Pool rate  = $120,000 / 200 runs = $600 / run\nProduct Z = 25 runs × $600  = $15,000",
    syllabus: 'PM • Section B2 — Activity-based costing',
  },
  {
    id: 'pm-002', topic: 'CVP Analysis', topicNum: 6, paper: 'PM',
    session: 'Mar/Jun 2024', type: 'single', difficulty: 'Easy', marks: 2,
    prompt: "A company sells one product at $40 per unit. Variable cost is $24 and fixed costs are $96,000 per month. What is the break-even point in units?",
    options: { A: '2,400 units', B: '4,000 units', C: '6,000 units', D: '24,000 units' },
    correct: 'C',
    explanation: "Contribution per unit = $40 − $24 = $16. Break-even = Fixed costs ÷ Contribution = $96,000 ÷ $16 = 6,000 units.",
    calc: "Contribution    = $40 − $24 = $16/u\nBreak-even (u) = $96,000 / $16 = 6,000 units",
    syllabus: 'PM • Section C1 — Cost–volume–profit analysis',
  },
  {
    id: 'pm-003', topic: 'Variance Analysis', topicNum: 13, paper: 'PM',
    session: 'Sep/Dec 2024', type: 'multi', difficulty: 'Hard', marks: 2,
    prompt: "Which TWO of the following would cause an ADVERSE direct material price variance?",
    options: {
      A: 'A bulk-order discount was negotiated with the supplier',
      B: 'The standard price was set at the start of the year and inflation has since eroded purchasing power',
      C: 'A switch to a higher-grade material was made during the period',
      D: 'Workers became more efficient and produced more output per hour',
      E: 'A quality control issue caused 5% of materials purchased to be unusable',
    },
    correct: ['B', 'C'],
    explanation: "Inflation increases the actual price paid above standard (B). Switching to a higher-grade material increases price (C). Bulk discount (A) would be FAVOURABLE. Efficiency (D) affects USAGE not price.",
    syllabus: 'PM • Section D2 — Standard costing and variance analysis',
  },
  {
    id: 'pm-004', topic: 'Relevant Costing', topicNum: 7, paper: 'PM',
    session: 'Mar/Jun 2024', type: 'single', difficulty: 'Medium', marks: 2,
    prompt: "A company has 400kg of material X in inventory which originally cost $8/kg. The material has no other use and would be sold as scrap for $3/kg. A special contract requires 500kg of material X. The current purchase price is $10/kg. What is the relevant cost of material X for the contract?",
    options: { A: '$2,200', B: '$2,800', C: '$3,200', D: '$5,000' },
    correct: 'A',
    explanation: "400kg in stock — opportunity cost = scrap value forgone = 400 × $3 = $1,200. Additional 100kg purchased at current price = 100 × $10 = $1,000. Total relevant cost = $2,200.",
    calc: "In stock (400kg @ scrap $3)   = $1,200\nPurchase (100kg @ $10)        = $1,000\nRelevant cost                  = $2,200",
    syllabus: 'PM • Section C2 — Relevant cost analysis',
  },
  {
    id: 'pm-005', topic: 'Performance Measurement', topicNum: 18, paper: 'PM',
    session: 'Sep/Dec 2024', type: 'single', difficulty: 'Easy', marks: 2,
    prompt: "A division has profit of $480,000 on capital employed of $3,000,000. The group's cost of capital is 12%. What is the division's RESIDUAL INCOME?",
    options: { A: '$120,000', B: '$360,000', C: '$480,000', D: '$840,000' },
    correct: 'A',
    explanation: "Residual Income = Profit − (Capital Employed × Cost of Capital) = $480,000 − ($3,000,000 × 12%) = $480,000 − $360,000 = $120,000.",
    calc: "Imputed charge = $3,000,000 × 12% = $360,000\nRI             = $480,000 − $360,000 = $120,000",
    syllabus: 'PM • Section E2 — Divisional performance and transfer pricing',
  },
  {
    id: 'pm-006', topic: 'Limiting Factor', topicNum: 7, paper: 'PM',
    session: 'Mar/Jun 2024', type: 'single', difficulty: 'Medium', marks: 2,
    prompt: "Three products use the same machine. Product X earns contribution of $24/unit using 4 hours, Y earns $30/unit using 3 hours, Z earns $40/unit using 8 hours. With limited machine hours, which is the optimal production priority?",
    options: { A: 'Z, Y, X', B: 'Y, X, Z', C: 'X, Y, Z', D: 'Y, Z, X' },
    correct: 'B',
    explanation: "Rank by contribution per limiting-factor hour. X: 24/4 = $6. Y: 30/3 = $10. Z: 40/8 = $5. Priority: Y ($10), X ($6), Z ($5).",
    calc: "X = $24 / 4h = $6.00 per hour\nY = $30 / 3h = $10.00 per hour\nZ = $40 / 8h = $5.00 per hour\n→ Rank Y, X, Z",
    syllabus: 'PM • Section C2 — Limiting factor analysis',
  },
]

export const TOPICS = [
  { num: 1,  name: 'Costing concepts',                 strength: 82 },
  { num: 2,  name: 'Absorption & marginal costing',    strength: 76 },
  { num: 3,  name: 'Throughput accounting',            strength: 65 },
  { num: 4,  name: 'Activity-based costing',           strength: 41 },
  { num: 5,  name: 'Target & life-cycle costing',      strength: 58 },
  { num: 6,  name: 'CVP analysis',                     strength: 88 },
  { num: 7,  name: 'Relevant costing & limiting factors', strength: 49 },
  { num: 8,  name: 'Pricing decisions',                strength: 71 },
  { num: 9,  name: 'Risk and uncertainty',             strength: 38 },
  { num: 10, name: 'Budgeting techniques',             strength: 67 },
  { num: 11, name: 'Quantitative analysis',            strength: 55 },
  { num: 12, name: 'Standard costing',                 strength: 72 },
  { num: 13, name: 'Variance analysis',                strength: 46 },
  { num: 14, name: 'Performance measurement systems',  strength: 60 },
  { num: 15, name: 'Financial performance measures',   strength: 74 },
  { num: 16, name: 'Non-financial measures',           strength: 80 },
  { num: 17, name: 'Divisional performance',           strength: 53 },
  { num: 18, name: 'Transfer pricing',                 strength: 62 },
]

export const SEED_MOCKS = [
  { id: 'm-019', name: 'Full Mock #19', subject: 'PM', date: '2026-04-28', duration: '3h 04m', score: 78, total: 100, sectionA: 28, sectionB: 24, sectionC: 26, weakTopic: 'Activity-based costing' },
  { id: 'm-018', name: 'PM Quick Mock', subject: 'PM', date: '2026-04-23', duration: '1h 12m', score: 64, total: 100, sectionA: 22, sectionB: 18, sectionC: 24, weakTopic: 'Variance analysis' },
  { id: 'm-017', name: 'Section A Drill', subject: 'PM', date: '2026-04-19', duration: '0h 48m', score: 81, total: 100, sectionA: 32, sectionB: 0, sectionC: 0, weakTopic: 'Risk and uncertainty' },
  { id: 'm-016', name: 'Full Mock #16', subject: 'PM', date: '2026-04-14', duration: '2h 58m', score: 56, total: 100, sectionA: 21, sectionB: 17, sectionC: 18, weakTopic: 'Activity-based costing' },
  { id: 'm-015', name: 'Topic Drill — ABC', subject: 'PM', date: '2026-04-09', duration: '0h 36m', score: 49, total: 100, sectionA: 14, sectionB: 0, sectionC: 0, weakTopic: 'Activity-based costing' },
  { id: 'm-014', name: 'Full Mock #14', subject: 'PM', date: '2026-04-04', duration: '3h 02m', score: 71, total: 100, sectionA: 26, sectionB: 22, sectionC: 23, weakTopic: 'Relevant costing' },
  { id: 'm-013', name: 'Quick Variance Mock', subject: 'PM', date: '2026-03-29', duration: '0h 52m', score: 58, total: 100, sectionA: 17, sectionB: 19, sectionC: 0, weakTopic: 'Variance analysis' },
  { id: 'm-012', name: 'Full Mock #12', subject: 'PM', date: '2026-03-23', duration: '2h 51m', score: 67, total: 100, sectionA: 25, sectionB: 20, sectionC: 22, weakTopic: 'Risk and uncertainty' },
]

export const LEADERBOARD = [
  { name: 'Aarav K.', score: 94, mocks: 32, color: '#5B5BFF' },
  { name: 'Rina P.',  score: 91, mocks: 28, color: '#22D3EE' },
  { name: 'Diego M.', score: 85, mocks: 22, color: '#8B5CF6' },
  { name: 'Sara H.',  score: 81, mocks: 19, color: '#16A37B' },
  { name: 'Chen W.',  score: 79, mocks: 17, color: '#FF7A45' },
]
